### ISSUE TITLE
Add support for .NET 4.5.x / 4.6.x

### ISSUE THREAD

**Issue by ogreenz** [DotNetCross/Memory.Unsafe#6]
Is there any real reason why this library can't be targeted for .NET 4.x?

I've previously had similar code running in .NET 2.0...

I successfully compiled it and added it to my VS proj running:
ilasm /dll /optimize .\il\DotNetCross.Memory.Unsafe.il /OUTPUT=.\build\DotNetCross.Memory.Unsafe.dll

**Comment by nietras** [comment]
It should work fine for 4.x. We have used it for such, otherwise there is another packaging issue. Could you make a more detailed set of steps to reproduce the error?

Be aware that MS has finished a dev build of there own `Unsafe` class that you could use. See https://github.com/dotnet/corefx/pull/7966

**Comment by ogreenz** [comment]
Clean install of VS 2015 on Windows 10, installing the package from a NuGet would give a "Failed to add reference to System.Runtime". When I compile it myself as I showed above it works.

**Comment by nietras** [comment]
For which project type? Using Update 1 or 2?

> When I compile it myself as I showed above it works.

If you unzip the `nupkg` and copy the `dll` I am sure it would work too. This is a nuget packaging issue or nuget client issue so I need more info on that and the specific  error message.

**Comment by nietras** [comment]
I think the problem is the packaging within the `dotnet` moniker in the package. This simply does not work. When creating a new .NET 4.5 console project and then adding `DotNetCross.Memory.Unsafe` via nuget to the project it will ask for agreeing to license for `System.Runtime` and then try to install both. However, this failed on my machine with:
````
Attempting to gather dependency information for package 'DotNetCross.Memory.Unsafe.0.2.3' with respect to project 'UnsafeTest', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'DotNetCross.Memory.Unsafe.0.2.3' with DependencyBehavior 'Lowest'
Resolving actions to install package 'DotNetCross.Memory.Unsafe.0.2.3'
Resolved actions to install package 'DotNetCross.Memory.Unsafe.0.2.3'
Adding package 'System.Runtime.4.0.0' to folder 'D:\temp\UnsafeTest\packages'
Added package 'System.Runtime.4.0.0' to folder 'D:\temp\UnsafeTest\packages'
Added package 'System.Runtime.4.0.0' to 'packages.config'
Successfully installed 'System.Runtime 4.0.0' to UnsafeTest
Adding package 'DotNetCross.Memory.Unsafe.0.2.3' to folder 'D:\temp\UnsafeTest\packages'
Added package 'DotNetCross.Memory.Unsafe.0.2.3' to folder 'D:\temp\UnsafeTest\packages'
Install failed. Rolling back...
Package 'DotNetCross.Memory.Unsafe.0.2.3 : System.Runtime [4.0.0, )' does not exist in project 'UnsafeTest'
Removed package 'System.Runtime.4.0.0' from 'packages.config'
Removing package 'DotNetCross.Memory.Unsafe.0.2.3 : System.Runtime [4.0.0, )' from folder 'D:\temp\UnsafeTest\packages'
Removed package 'DotNetCross.Memory.Unsafe.0.2.3 : System.Runtime [4.0.0, )' from folder 'D:\temp\UnsafeTest\packages'
Removing package 'System.Runtime.4.0.0' from folder 'D:\temp\UnsafeTest\packages'
Removed package 'System.Runtime.4.0.0' from folder 'D:\temp\UnsafeTest\packages'
Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.
```

The problem is, though, that is should never ask for installing for .NET 4.5 since is should use the framework assembly, but instead it seems to use the nuspec configuration for `dotnet` so this packaging moniker simpy does not work. Changing this, though, risks breaking the package usage for .NET Core. @jamesqo any idea how we can remove the `dotnet` in spec or change it to avoid issues in .NET 4.5?

**Comment by nietras** [comment]
I think I fixed the issue, please let me know if not. I tested it by making a local packages folder and installing it on different project types.

I have copied the packaging from the new `System.Runtime.CompilerServices.Unsafe` package (discussed at https://github.com/dotnet/corefx/pull/7966) which is available from corefx dev feed https://dotnet.myget.org/F/dotnet-core
